import type { CompanyRecord, ContactRecord, FollowUpItem, IntakeDocumentRecord, IntakeSignal, ProjectRecord, TaskItem } from '../types';

const today = new Date();
const day = (offset: number) => {
  const copy = new Date(today);
  copy.setDate(copy.getDate() + offset);
  return copy.toISOString();
};

export const starterCompanies: CompanyRecord[] = [
  { id: 'CO-001', name: 'NAVFAC NW', type: 'Government', notes: 'Government customer and reviewer.', tags: ['Government', 'Owner'] },
  { id: 'CO-002', name: 'Fire Sprinkler West', type: 'Subcontractor', notes: 'Sprinkler subcontractor.', tags: ['Fire Protection'] },
  { id: 'CO-003', name: 'Northwest Vendor Supply', type: 'Vendor', notes: 'Vendor used for buyout and quote tracking.', tags: ['Vendor'] },
  { id: 'CO-004', name: 'WA Patriot Internal', type: 'Internal', notes: 'Internal owner bucket.', tags: ['Internal'] },
];

export const starterContacts: ContactRecord[] = [
  { id: 'CT-001', name: 'Alex Kushner', email: 'alex.kushner@example.mil', companyId: 'CO-001', role: 'CM', notes: 'NAVFAC CM', tags: ['Government'] },
  { id: 'CT-002', name: 'Scott Blair', email: 'scott.blair@example.mil', companyId: 'CO-001', role: 'KO', notes: 'KO contact', tags: ['Government'] },
  { id: 'CT-003', name: 'Jeff', email: 'jeff@example.com', companyId: 'CO-002', role: 'PM', notes: 'Fire sprinkler sub lead', tags: ['Sub'] },
  { id: 'CT-004', name: 'Vendor Desk', email: 'quotes@example.com', companyId: 'CO-003', role: 'Sales', notes: 'Quote desk', tags: ['Vendor'] },
];

export const starterProjects: ProjectRecord[] = [
  { id: 'PRJ-001', name: 'B995 Weld Shop', owner: 'Jared', status: 'Active', notes: 'Primary active buyout and coordination project.', tags: ['Design-Build', 'NAVFAC'], createdAt: day(-40), updatedAt: day(0) },
  { id: 'PRJ-002', name: 'B880 Chillers', owner: 'Andrew', status: 'Closeout', notes: 'Commissioning and closeout push.', tags: ['Closeout', 'Cx'], createdAt: day(-60), updatedAt: day(-1) },
  { id: 'PRJ-003', name: 'General', systemProjectKind: 'unclassified', owner: 'Jared', status: 'Active', notes: 'Catch-all for work not yet classified.', tags: ['General'], createdAt: day(-90), updatedAt: day(-2) },
];

export const starterItems: FollowUpItem[] = [
  {
    id: 'FUP-001',
    title: 'Follow up with NAVFAC on RFI 22 determination',
    source: 'Email',
    project: 'B995 Weld Shop',
    projectId: 'PRJ-001',
    owner: 'Jared',
    status: 'Waiting on external',
    priority: 'Critical',
    dueDate: day(-1),
    promisedDate: day(-2),
    lastTouchDate: day(-5),
    nextTouchDate: day(0),
    lastNudgedAt: day(-5),
    nextAction: 'Send concise follow-up email to KO and log response date.',
    summary: 'BAA non-availability request sent. No response after five days.',
    tags: ['NAVFAC', 'RFI', 'Decision'],
    sourceRef: 'Dropped email file: 01_b995_rfi_followup.eml',
    sourceRefs: ['Dropped email file: 01_b995_rfi_followup.eml'],
    mergedItemIds: [],
    waitingOn: 'KO decision',
    notes: 'This needs to stay visible until a formal answer is received.',
    timeline: [
      { id: 't1', at: day(-7), type: 'created', summary: 'Item created from outbound email.' },
      { id: 't2', at: day(-5), type: 'nudged', summary: 'Checked inbox and no response found.' },
    ],
    category: 'RFI',
    owesNextAction: 'Government',
    escalationLevel: 'Escalate',
    cadenceDays: 3,
    contactId: 'CT-002',
    companyId: 'CO-001',
    threadKey: 'B995-RFI22',
    draftFollowUp: '',
  },
  {
    id: 'FUP-002',
    title: 'Review sprinkler outage phasing and fire watch cost path',
    source: 'Notes',
    project: 'B995 Weld Shop',
    projectId: 'PRJ-001',
    owner: 'Jared',
    status: 'Needs action',
    priority: 'High',
    dueDate: day(1),
    promisedDate: day(2),
    lastTouchDate: day(0),
    nextTouchDate: day(1),
    nextAction: 'Send three-option direction email to fire sprinkler sub.',
    summary: 'Meeting notes captured a needed decision on outage plan and fire watch cost handling.',
    tags: ['Fire Protection', 'Cost', 'Coordination'],
    sourceRef: 'Meeting notes 03-31',
    sourceRefs: ['Meeting notes 03-31'],
    mergedItemIds: [],
    waitingOn: 'Jeff response',
    notes: 'Need a clean record showing options and cost responsibility.',
    timeline: [
      { id: 't3', at: day(0), type: 'imported', summary: 'Imported from meeting notes.' },
    ],
    category: 'Coordination',
    owesNextAction: 'Subcontractor',
    escalationLevel: 'Watch',
    cadenceDays: 2,
    contactId: 'CT-003',
    companyId: 'CO-002',
    threadKey: 'FSW-OUTAGE',
    draftFollowUp: '',
  },
  {
    id: 'FUP-003',
    title: 'Update commissioning milestones tracker and closeout log',
    source: 'Excel',
    project: 'B880 Chillers',
    projectId: 'PRJ-002',
    owner: 'Andrew',
    status: 'In progress',
    priority: 'Medium',
    dueDate: day(2),
    promisedDate: day(4),
    lastTouchDate: day(-1),
    nextTouchDate: day(1),
    nextAction: 'Refresh milestone dates and attach latest evidence to closeout package.',
    summary: 'Excel issue log shows open action on closeout tracking.',
    tags: ['Cx', 'Closeout', 'Schedule'],
    sourceRef: 'Issues Tracker.xlsx row 47',
    sourceRefs: ['Issues Tracker.xlsx row 47'],
    mergedItemIds: [],
    notes: 'Should be linked to the final commissioning folder.',
    timeline: [
      { id: 't4', at: day(-4), type: 'imported', summary: 'Imported from spreadsheet row.' },
      { id: 't5', at: day(-1), type: 'status_changed', summary: 'Marked in progress after owner update.' },
    ],
    category: 'Closeout',
    owesNextAction: 'Internal',
    escalationLevel: 'None',
    cadenceDays: 4,
    companyId: 'CO-004',
    threadKey: 'B880-CX-CLOSEOUT',
    draftFollowUp: '',
  },
  {
    id: 'FUP-004',
    title: 'Confirm whether submittals must be reissued after CCD revision',
    source: 'To-do',
    project: 'B995 Weld Shop',
    projectId: 'PRJ-001',
    owner: 'Jared',
    status: 'Needs action',
    priority: 'Medium',
    dueDate: day(3),
    promisedDate: day(5),
    lastTouchDate: day(-2),
    nextTouchDate: day(1),
    nextAction: 'Ask CM if revised CCD requires submittal resubmission.',
    summary: 'Open question tied to revised contract completion date handling.',
    tags: ['Submittals', 'CCD'],
    sourceRef: 'Todo list',
    sourceRefs: ['Todo list'],
    mergedItemIds: [],
    waitingOn: 'CM guidance',
    notes: 'Important to avoid unnecessary resubmission work.',
    timeline: [
      { id: 't6', at: day(-2), type: 'created', summary: 'Created manually from planning list.' },
    ],
    category: 'Submittal',
    owesNextAction: 'Government',
    escalationLevel: 'None',
    cadenceDays: 3,
    contactId: 'CT-001',
    companyId: 'CO-001',
    threadKey: 'B995-CCD-SUBMITTALS',
    draftFollowUp: '',
  },
  {
    id: 'FUP-005',
    title: 'Vendor quote has gone stale without response',
    source: 'Email',
    project: 'General',
    projectId: 'PRJ-003',
    owner: 'Mike',
    status: 'At risk',
    priority: 'High',
    dueDate: day(-3),
    promisedDate: day(-1),
    lastTouchDate: day(-11),
    nextTouchDate: day(-1),
    lastNudgedAt: day(-8),
    nextAction: 'Call vendor and capture verbal update in timeline.',
    summary: 'No reply received after quote request. Risk to buyout timing.',
    tags: ['Vendor', 'Buyout'],
    sourceRef: 'Inbox thread Vendor RFQ',
    sourceRefs: ['Inbox thread Vendor RFQ'],
    mergedItemIds: [],
    waitingOn: 'Vendor quote',
    notes: 'Escalate if no answer after call.',
    timeline: [
      { id: 't7', at: day(-11), type: 'created', summary: 'Created from outbound RFQ.' },
    ],
    category: 'Procurement',
    owesNextAction: 'Vendor',
    escalationLevel: 'Critical',
    cadenceDays: 2,
    contactId: 'CT-004',
    companyId: 'CO-003',
    threadKey: 'RFQ-VENDOR-001',
    draftFollowUp: '',
  },
];

export const starterSignals: IntakeSignal[] = [
  {
    id: 'SIG-001',
    source: 'Email',
    title: 'No response found for BAA request after 5 days',
    detail: 'Rule suggestion: convert this thread into a tracked follow-up or escalate existing record.',
    urgency: 'High',
  },
  {
    id: 'SIG-002',
    source: 'Excel',
    title: 'Issue tracker row is overdue',
    detail: 'Spreadsheet row indicates overdue issue with no recent touch date.',
    urgency: 'High',
  },
  {
    id: 'SIG-003',
    source: 'Notes',
    title: 'Action language detected in meeting notes',
    detail: 'Potential task found with no owner or due date assigned yet.',
    urgency: 'Medium',
  },
  {
    id: 'SIG-004',
    source: 'To-do',
    title: 'Todo item has no linked project',
    detail: 'This should be classified before it is allowed into the main tracker.',
    urgency: 'Low',
  },
];

export const starterIntakeDocuments: IntakeDocumentRecord[] = [
  {
    id: 'DOC-001',
    name: 'B995 Issue Tracker.xlsx',
    kind: 'Spreadsheet',
    disposition: 'Unprocessed',
    projectId: 'PRJ-001',
    project: 'B995 Weld Shop',
    owner: 'Jared',
    sourceRef: 'Uploaded manually to intake',
    uploadedAt: day(0),
    notes: 'Needs triage for open issue rows.',
    tags: ['Excel', 'Issues'],
  },
  {
    id: 'DOC-002',
    name: 'B880 Commissioning Notes.docx',
    kind: 'Document',
    disposition: 'Reference only',
    projectId: 'PRJ-002',
    project: 'B880 Chillers',
    owner: 'Andrew',
    sourceRef: 'Uploaded manually to intake',
    uploadedAt: day(-1),
    notes: 'Reference file for closeout coordination.',
    tags: ['Notes', 'Closeout'],
  },
];

export const starterTasks: TaskItem[] = [
  {
    id: 'TSK-001',
    title: 'Draft B995 demo scope package for buyout',
    project: 'B995 Weld Shop',
    projectId: 'PRJ-001',
    owner: 'Jared',
    status: 'In progress',
    priority: 'High',
    dueDate: day(1),
    startDate: day(-1),
    summary: 'Build the bid-ready demo scope with exclusions and supporting notes for subcontractor outreach.',
    nextStep: 'Finish exclusions and send package for internal review.',
    notes: 'Keep it tight to proposal language and avoid pushing design criteria downstream.',
    tags: ['Buyout', 'Scope', 'Demo'],
    linkedFollowUpId: 'FUP-002',
    companyId: 'CO-004',
    createdAt: day(-2),
    updatedAt: day(0),
  },
  {
    id: 'TSK-002',
    title: 'Update daily status email with B995 subcontract progress',
    project: 'B995 Weld Shop',
    projectId: 'PRJ-001',
    owner: 'Jared',
    status: 'To do',
    priority: 'Medium',
    dueDate: day(0),
    startDate: day(0),
    summary: 'Add the latest buyout, subcontract, and action item updates for leadership.',
    nextStep: 'Pull current buyout status and draft concise bullets.',
    notes: 'Keep it split between concise summary and forward-looking detail.',
    tags: ['Reporting', 'Leadership'],
    companyId: 'CO-004',
    createdAt: day(-1),
    updatedAt: day(-1),
  },
  {
    id: 'TSK-003',
    title: 'Prepare closeout evidence folder for B880 commissioning items',
    project: 'B880 Chillers',
    projectId: 'PRJ-002',
    owner: 'Andrew',
    status: 'Blocked',
    priority: 'Medium',
    dueDate: day(3),
    startDate: day(-3),
    summary: 'Collect remaining trend logs, training evidence, and test records into one clean handoff folder.',
    nextStep: 'Wait for final trending export, then finish file structure.',
    notes: 'Blocked until the final DDC evidence lands.',
    tags: ['Closeout', 'Cx'],
    linkedFollowUpId: 'FUP-003',
    createdAt: day(-4),
    updatedAt: day(-1),
  },
];
