import { parseForwardedProviderPayload } from '../../lib/forwardedEmailParser';
import { buildForwardingAudit, buildForwardingCandidate, buildForwardedLedgerEntry, buildTaskFromForwarded, routeForwardedEmail } from '../../lib/intakeRouting';
import { evaluateForwardedImportSafety } from '../../lib/intakeImportSafety';
import { appendReviewerFeedback } from '../../domains/shared/audit';
import { buildFollowUpFromForwarded, normalizeItems } from '../../domains/followups/helpers';
import { normalizeTasks } from '../../domains/tasks/helpers';
import { enforceFollowUpIntegrity, enforceTaskIntegrity } from '../../domains/records/integrity';
import { createId, todayIso } from '../../lib/utils';
import type { AppStore, AppStoreActions } from '../types';
import type { SliceContext, SliceSet } from './types';
import { refreshDuplicates } from '../useCases/mutationEffects';

export function createForwardingSlice(set: SliceSet, { queuePersist }: SliceContext): Pick<AppStoreActions,
  'ingestForwardedEmailPayload' | 'approveForwardedCandidate' | 'rejectForwardedCandidate' | 'saveForwardedCandidateAsReference' | 'linkForwardedCandidateToExisting' | 'addForwardRuleFromCandidate' | 'addManualForwardRule' | 'updateForwardRule' | 'deleteForwardRule'
> {
  return {
    ingestForwardedEmailPayload: (payload) => { const record = parseForwardedProviderPayload(payload); set((state: AppStore) => { const route = routeForwardedEmail(record, { rules: state.forwardedRules, ledger: state.forwardedLedger, items: state.items, tasks: state.tasks, candidates: state.forwardedCandidates, internalDomains: ['followuphq.com'] }); let items = state.items; let tasks = state.tasks; let intakeDocuments = state.intakeDocuments; let createdTaskId: string | undefined; let createdFollowUpId: string | undefined; let candidate = state.forwardedCandidates; const owner = route.ruleOwner ?? record.parsedCommandHints.owner ?? ''; const project = route.ruleProject ?? record.parsedCommandHints.project ?? record.parsedProjectHints[0] ?? ''; if (route.decision === 'auto-task') { const task = enforceTaskIntegrity(buildTaskFromForwarded(record, owner, project), state.projects); tasks = normalizeTasks([task, ...state.tasks]); createdTaskId = task.id; } else if (route.decision === 'auto-followup') { const item = enforceFollowUpIntegrity(buildFollowUpFromForwarded(record, owner, project), state.projects); items = normalizeItems([item, ...state.items]); createdFollowUpId = item.id; } else if (route.decision === 'review') { const alreadyQueued = state.forwardedCandidates.some((entry) => entry.forwardedEmailId === record.id || (entry.normalizedSubject === record.normalizedSubject && entry.originalSender.toLowerCase() === record.originalSender.toLowerCase() && entry.status === 'pending')); if (!alreadyQueued) candidate = [buildForwardingCandidate(record, route), ...state.forwardedCandidates]; } else if (route.decision === 'reference') { intakeDocuments = [{ id: createId('DOC'), name: record.originalSubject || 'Forwarded email reference', kind: 'Text', disposition: 'Reference only', project, owner, sourceRef: `Forwarded/${record.id}`, uploadedAt: todayIso(), notes: record.bodyText.slice(0, 600), tags: ['Forwarded Intake', 'Reference'] }, ...state.intakeDocuments]; }
      return { items, tasks, intakeDocuments, forwardedEmails: [record, ...state.forwardedEmails].slice(0, 500), forwardedCandidates: candidate, forwardedLedger: [buildForwardedLedgerEntry(record, route, { taskId: createdTaskId, followUpId: createdFollowUpId }), ...state.forwardedLedger].slice(0, 1000), forwardedRoutingAudit: [buildForwardingAudit(record, route, { taskId: createdTaskId, followUpId: createdFollowUpId }), ...state.forwardedRoutingAudit].slice(0, 1000), duplicateReviews: refreshDuplicates(items, state.dismissedDuplicatePairs) };
    }); queuePersist(); },
    approveForwardedCandidate: (candidateId, asType, options) => { set((state: AppStore) => { const candidate = state.forwardedCandidates.find((entry) => entry.id === candidateId); if (!candidate || candidate.status !== 'pending') return state; const record = state.forwardedEmails.find((entry) => entry.id === candidate.forwardedEmailId); if (!record) return state; const type = asType ?? (candidate.suggestedType === 'followup' ? 'followup' : 'task'); const safety = evaluateForwardedImportSafety(candidate); if (!safety.safeToCreateNew && !options?.overrideUnsafeCreate) return state; const ruleIds = state.forwardedRoutingAudit.find((entry) => entry.forwardedEmailId === candidate.forwardedEmailId)?.ruleIds ?? []; if (type === 'task') { const task = enforceTaskIntegrity(buildTaskFromForwarded(record, record.parsedCommandHints.owner ?? '', candidate.parsedProject ?? ''), state.projects); return { tasks: normalizeTasks([task, ...state.tasks]), forwardedCandidates: state.forwardedCandidates.map((entry) => entry.id === candidateId ? { ...entry, status: 'approved', createdTaskId: task.id, updatedAt: todayIso() } : entry), intakeReviewerFeedback: appendReviewerFeedback(state.intakeReviewerFeedback, { source: 'forwarding', candidateId: candidate.id, candidateKind: 'forwarded', forwardedEmailId: candidate.forwardedEmailId, suggestedType: candidate.suggestedType, suggestedAction: 'create_new', finalDecision: 'approved_task', overrideApplied: candidate.suggestedType !== 'task', correctedFields: candidate.suggestedType !== 'task' ? ['type'] : [], duplicateRiskOverride: !safety.safeToCreateNew && !!options?.overrideUnsafeCreate, ruleIds }) }; }
      const item = enforceFollowUpIntegrity(buildFollowUpFromForwarded(record, record.parsedCommandHints.owner ?? '', candidate.parsedProject ?? ''), state.projects); const items = normalizeItems([item, ...state.items]); return { items, duplicateReviews: refreshDuplicates(items, state.dismissedDuplicatePairs), forwardedCandidates: state.forwardedCandidates.map((entry) => entry.id === candidateId ? { ...entry, status: 'approved', createdFollowUpId: item.id, updatedAt: todayIso() } : entry), intakeReviewerFeedback: appendReviewerFeedback(state.intakeReviewerFeedback, { source: 'forwarding', candidateId: candidate.id, candidateKind: 'forwarded', forwardedEmailId: candidate.forwardedEmailId, suggestedType: candidate.suggestedType, suggestedAction: 'create_new', finalDecision: 'approved_followup', overrideApplied: candidate.suggestedType !== 'followup', correctedFields: candidate.suggestedType !== 'followup' ? ['type'] : [], duplicateRiskOverride: !safety.safeToCreateNew && !!options?.overrideUnsafeCreate, ruleIds }) }; }); queuePersist(); },
    rejectForwardedCandidate: (candidateId) => { set((state: AppStore) => { const candidate = state.forwardedCandidates.find((entry) => entry.id === candidateId); if (!candidate) return state; const ruleIds = state.forwardedRoutingAudit.find((entry) => entry.forwardedEmailId === candidate.forwardedEmailId)?.ruleIds ?? []; return { forwardedCandidates: state.forwardedCandidates.map((entry) => entry.id === candidateId ? { ...entry, status: 'rejected', updatedAt: todayIso() } : entry), intakeReviewerFeedback: appendReviewerFeedback(state.intakeReviewerFeedback, { source: 'forwarding', candidateId: candidate.id, candidateKind: 'forwarded', forwardedEmailId: candidate.forwardedEmailId, suggestedType: candidate.suggestedType, suggestedAction: 'create_new', finalDecision: 'rejected', overrideApplied: true, correctedFields: [], ruleIds }) }; }); queuePersist(); },
    saveForwardedCandidateAsReference: (candidateId) => { set((state: AppStore) => { const candidate = state.forwardedCandidates.find((entry) => entry.id === candidateId); if (!candidate) return state; const ruleIds = state.forwardedRoutingAudit.find((entry) => entry.forwardedEmailId === candidate.forwardedEmailId)?.ruleIds ?? []; return { forwardedCandidates: state.forwardedCandidates.map((entry) => entry.id === candidateId ? { ...entry, status: 'reference', updatedAt: todayIso() } : entry), intakeReviewerFeedback: appendReviewerFeedback(state.intakeReviewerFeedback, { source: 'forwarding', candidateId: candidate.id, candidateKind: 'forwarded', forwardedEmailId: candidate.forwardedEmailId, suggestedType: candidate.suggestedType, suggestedAction: 'create_new', finalDecision: 'saved_reference', overrideApplied: candidate.suggestedType !== 'reference', correctedFields: [], ruleIds }) }; }); queuePersist(); },
    linkForwardedCandidateToExisting: (candidateId, itemId) => { set((state: AppStore) => { const candidate = state.forwardedCandidates.find((entry) => entry.id === candidateId); if (!candidate) return state; const ruleIds = state.forwardedRoutingAudit.find((entry) => entry.forwardedEmailId === candidate.forwardedEmailId)?.ruleIds ?? []; return { forwardedCandidates: state.forwardedCandidates.map((entry) => entry.id === candidateId ? { ...entry, status: 'linked', linkedItemId: itemId, updatedAt: todayIso() } : entry), intakeReviewerFeedback: appendReviewerFeedback(state.intakeReviewerFeedback, { source: 'forwarding', candidateId: candidate.id, candidateKind: 'forwarded', forwardedEmailId: candidate.forwardedEmailId, suggestedType: candidate.suggestedType, suggestedAction: 'create_new', finalDecision: 'linked_existing', overrideApplied: true, correctedFields: ['linking_decision'], ruleIds }) }; }); queuePersist(); },
    addForwardRuleFromCandidate: (candidateId, action) => { set((state: AppStore) => { const candidate = state.forwardedCandidates.find((entry) => entry.id === candidateId); if (!candidate) return state; return { forwardedRules: [...state.forwardedRules, { id: createId('FWR'), name: `From candidate: ${candidate.normalizedSubject.slice(0, 40)}`, enabled: true, priority: (state.forwardedRules.at(-1)?.priority ?? 100) + 10, source: 'user', conditions: { forwardingAlias: candidate.forwardingAlias, senderEmailContains: candidate.originalSender, subjectContains: candidate.normalizedSubject.slice(0, 20) }, action, createdAt: todayIso(), updatedAt: todayIso() }] }; }); queuePersist(); },
    addManualForwardRule: (ruleInput) => { set((state: AppStore) => ({ forwardedRules: [...state.forwardedRules, { ...ruleInput, id: createId('FWR'), source: 'user', createdAt: todayIso(), updatedAt: todayIso() }] })); queuePersist(); },
    updateForwardRule: (ruleId, patch) => { set((state: AppStore) => ({ forwardedRules: state.forwardedRules.map((rule) => rule.id === ruleId ? { ...rule, ...patch, updatedAt: todayIso() } : rule) })); queuePersist(); },
    deleteForwardRule: (ruleId) => { set((state: AppStore) => ({ forwardedRules: state.forwardedRules.filter((rule) => rule.id !== ruleId) })); queuePersist(); },
  };
}
