import { isTauriRuntime } from '../../lib/persistence';
import { buildFollowUpFromOutlookImport, normalizeItems } from '../../domains/followups/helpers';
import { todayIso } from '../../lib/utils';
import { enforceFollowUpIntegrity } from '../../domains/records/integrity';
import type { OutlookConnectionState } from '../../types';
import type { AppStoreActions, AppStore } from '../types';
import type { SliceContext, SliceGet, SliceSet } from './types';
import { refreshDuplicates } from '../useCases/mutationEffects';

async function ensureValidOutlookAccessToken(connection: OutlookConnectionState): Promise<OutlookConnectionState> {
  if (!connection.tokens) throw new Error('Connect Outlook before syncing.');
  const graph = await import('../../lib/outlookGraph');
  if (!graph.isTokenExpired(connection.tokens)) return connection;
  if (!connection.tokens.refreshToken) throw new Error('Missing refresh token. Reconnect Outlook.');
  const tokens = await graph.refreshAccessToken(connection.settings, connection.tokens.refreshToken);
  return { ...connection, tokens };
}

export function createOutlookSlice(set: SliceSet, get: SliceGet, { queuePersist }: SliceContext, defaultOutlookConnection: OutlookConnectionState): Pick<AppStoreActions,
  'updateOutlookSettings' | 'startOutlookAuth' | 'completeOutlookAuth' | 'syncOutlookMailbox' | 'importOutlookMessage' | 'disconnectOutlook' | 'clearOutlookError'
> {
  return {
    updateOutlookSettings: (patch) => { set((state: AppStore) => ({ outlookConnection: { ...state.outlookConnection, settings: { ...state.outlookConnection.settings, ...patch } } })); queuePersist(); },
    startOutlookAuth: async () => { const { outlookConnection } = get(); if (!outlookConnection.settings.clientId.trim()) { set({ outlookConnection: { ...outlookConnection, syncStatus: 'error', lastError: 'Enter a Microsoft app registration client ID first.' } }); return; } const graph = await import('../../lib/outlookGraph'); let settings = outlookConnection.settings; if (isTauriRuntime()) { try { const api = await import('@tauri-apps/api/core'); const redirectUri = await api.invoke<string>('start_outlook_loopback_listener'); settings = { ...settings, redirectUri }; } catch (error) { set({ outlookConnection: { ...outlookConnection, syncStatus: 'error', lastError: error instanceof Error ? error.message : 'Failed to start Outlook callback listener.' } }); return; } } const { verifier, challenge } = await graph.generatePkcePair(); const stateToken = graph.generateState(); const authUrl = graph.buildAuthorizationUrl(settings, stateToken, challenge); set({ outlookConnection: { ...outlookConnection, settings, authSession: { pkceVerifier: verifier, state: stateToken, authUrl, startedAt: todayIso() }, syncStatus: 'auth-ready', lastError: undefined } }); queuePersist(); if (typeof window !== 'undefined') window.open(authUrl, '_blank', 'noopener,noreferrer'); },
    completeOutlookAuth: async (callbackUrl) => { try { const current = get().outlookConnection; if (!current.authSession) throw new Error('Start the Outlook sign-in first to generate a PKCE session.'); const graph = await import('../../lib/outlookGraph'); const { code, state } = graph.parseAuthorizationResponse(callbackUrl); if (state && state !== current.authSession.state) throw new Error('Returned OAuth state did not match the current sign-in session.'); const tokens = await graph.exchangeCodeForTokens(current.settings, code, current.authSession.pkceVerifier); const profile = await graph.fetchMailboxProfile(tokens.accessToken); set({ outlookConnection: { ...current, tokens, profile, mailboxLinked: true, authSession: undefined, syncStatus: 'connected', lastError: undefined } }); queuePersist(); } catch (error) { set((state: AppStore) => ({ outlookConnection: { ...state.outlookConnection, syncStatus: 'error', lastError: error instanceof Error ? error.message : 'Failed to complete Outlook sign-in.' } })); queuePersist(); } },
    syncOutlookMailbox: async () => { try { set((state: AppStore) => ({ outlookConnection: { ...state.outlookConnection, syncStatus: 'syncing', lastError: undefined } })); const graph = await import('../../lib/outlookGraph'); const connection = await ensureValidOutlookAccessToken(get().outlookConnection); set({ outlookConnection: connection }); let workingMessages = [...get().outlookMessages]; const syncFolders: Array<'inbox' | 'sentitems'> = connection.settings.autoPullSent ? ['inbox', 'sentitems'] : ['inbox']; let usedDelta = true; const nextCursor = { ...connection.syncCursorByFolder }; for (const folder of syncFolders) { const folderState = connection.syncCursorByFolder[folder] ?? {}; const result = await graph.fetchDeltaMessages(connection.tokens!.accessToken, folder, connection.settings.syncLimit, folderState.deltaLink); usedDelta = usedDelta && result.usedDelta; const folderMap = new Map(workingMessages.filter((entry) => entry.folder === folder).map((entry) => [entry.id, entry])); result.messages.forEach((message) => folderMap.set(message.id, message)); result.removedIds.forEach((messageId) => folderMap.delete(messageId)); const otherFolders = workingMessages.filter((entry) => entry.folder !== folder); const mergedFolder = Array.from(folderMap.values()).sort((a, b) => new Date(b.receivedDateTime ?? b.sentDateTime ?? 0).getTime() - new Date(a.receivedDateTime ?? a.sentDateTime ?? 0).getTime()).slice(0, Math.max(connection.settings.syncLimit * 2, 30)); workingMessages = [...otherFolders, ...mergedFolder]; nextCursor[folder] = { deltaLink: result.deltaLink ?? folderState.deltaLink, lastFolderSyncAt: todayIso(), lastMessageCount: mergedFolder.length }; }
      if (!connection.settings.autoPullSent) nextCursor.sentitems = connection.syncCursorByFolder.sentitems ?? {};
      const deduped = workingMessages.reduce<any[]>((acc, message) => { if (acc.some((entry) => entry.id === message.id)) return acc; acc.push(message); return acc; }, []).sort((a, b) => new Date(b.receivedDateTime ?? b.sentDateTime ?? 0).getTime() - new Date(a.receivedDateTime ?? a.sentDateTime ?? 0).getTime());
      set({ outlookConnection: { ...connection, syncStatus: 'connected', mailboxLinked: true, lastSyncAt: todayIso(), lastError: undefined, syncCursorByFolder: nextCursor, lastSyncMode: usedDelta ? 'delta' : 'initial' }, outlookMessages: deduped }); queuePersist();
    } catch (error) { set((state: AppStore) => ({ outlookConnection: { ...state.outlookConnection, syncStatus: 'error', lastError: error instanceof Error ? error.message : 'Mailbox sync failed.' } })); queuePersist(); } },
    importOutlookMessage: (messageId) => { const message = get().outlookMessages.find((entry) => entry.id === messageId); if (!message) return; const state = get(); const openConflict = state.items.some((item) => item.status !== 'Closed' && item.threadKey && message.conversationId && item.threadKey === message.conversationId); if (openConflict) return; const item = enforceFollowUpIntegrity(buildFollowUpFromOutlookImport(message, 'Jared', ''), state.projects); set((inner: AppStore) => { const items = normalizeItems([item, ...inner.items]); return { items, selectedId: item.id, duplicateReviews: refreshDuplicates(items, inner.dismissedDuplicatePairs) }; }); queuePersist(); },
    disconnectOutlook: () => { if (isTauriRuntime()) import('@tauri-apps/api/core').then((api) => api.invoke('clear_outlook_loopback_callback')).catch(() => undefined); set({ outlookConnection: defaultOutlookConnection, outlookMessages: [] }); queuePersist(); },
    clearOutlookError: () => set((state: AppStore) => ({ outlookConnection: { ...state.outlookConnection, lastError: undefined, syncStatus: state.outlookConnection.mailboxLinked ? 'connected' : 'idle' } })),
  };
}
