import { createId, todayIso, resolveProjectName, normalizeItem } from '../../lib/utils';
import { attachProjects } from '../../domains/followups/helpers';
import { normalizeTask } from '../../domains/tasks/helpers';
import { stampProject } from '../../domains/projects/helpers';
import type { IntakeDocumentRecord } from '../../types';
import type { AppStore, AppStoreActions } from '../types';
import type { SliceContext, SliceSet } from './types';

export function createProjectsSlice(set: SliceSet, { queuePersist }: SliceContext): Pick<AppStoreActions,
  'addProject' | 'updateProject' | 'reassignProjectRecords' | 'deleteProject' | 'addIntakeDocument' | 'updateIntakeDocument' | 'setIntakeDocumentDisposition' | 'deleteIntakeDocument'
> {
  return {
    addProject: (input) => { const id = createId('PRJ'); set((state: AppStore) => ({ projects: [...state.projects, { id, ...input, createdAt: todayIso(), updatedAt: todayIso() }].sort((a, b) => a.name.localeCompare(b.name)) })); queuePersist(); return id; },
    updateProject: (id, patch) => { set((state: AppStore) => { const original = state.projects.find((project) => project.id === id); const projects = state.projects.map((project) => (project.id === id ? stampProject(project, patch) : project)); const renamedTo = projects.find((project) => project.id === id)?.name ?? original?.name ?? 'General'; const items = original && patch.name && patch.name !== original.name ? attachProjects(state.items.map((item) => item.projectId === id ? normalizeItem({ ...item, project: renamedTo }) : item), projects) : attachProjects(state.items, projects); const tasks = state.tasks.map((task) => task.projectId === id ? normalizeTask({ ...task, project: renamedTo }) : task); const intakeDocuments = state.intakeDocuments.map((doc) => doc.projectId === id ? { ...doc, project: renamedTo } : doc); return { projects: projects.sort((a, b) => a.name.localeCompare(b.name)), items, tasks, intakeDocuments }; }); queuePersist(); },
    reassignProjectRecords: (fromProjectId, toProjectId, recordTypes = ['followups', 'tasks', 'docs']) => { set((state: AppStore) => { if (fromProjectId === toProjectId) return state; const target = state.projects.find((project) => project.id === toProjectId); if (!target) return state; const typeSet = new Set(recordTypes); const items = typeSet.has('followups') ? attachProjects(state.items.map((item) => item.projectId === fromProjectId ? normalizeItem({ ...item, projectId: target.id, project: target.name }) : item), state.projects) : state.items; const tasks = typeSet.has('tasks') ? state.tasks.map((task) => task.projectId === fromProjectId ? normalizeTask({ ...task, projectId: target.id, project: target.name }) : task) : state.tasks; const intakeDocuments = typeSet.has('docs') ? state.intakeDocuments.map((doc) => doc.projectId === fromProjectId ? { ...doc, projectId: target.id, project: target.name } : doc) : state.intakeDocuments; return { items, tasks, intakeDocuments }; }); queuePersist(); },
    deleteProject: (id, reassignToProjectId) => { set((state: AppStore) => { if (!state.projects.some((project) => project.id === id)) return state; const general = state.projects.find((project) => project.name === 'General') ?? { id: createId('PRJ'), name: 'General', owner: 'Unassigned', status: 'Active', notes: '', tags: ['General'], createdAt: todayIso(), updatedAt: todayIso() }; const existingProjects = state.projects.some((project) => project.id === general.id) ? state.projects : [...state.projects, general]; const targetProject = existingProjects.find((project) => project.id === reassignToProjectId && project.id !== id) ?? general; const projects = existingProjects.filter((project) => project.id !== id); const items = attachProjects(state.items.map((item) => item.projectId === id ? normalizeItem({ ...item, projectId: targetProject.id, project: targetProject.name }) : item), projects); const tasks = state.tasks.map((task) => task.projectId === id ? normalizeTask({ ...task, projectId: targetProject.id, project: targetProject.name }) : task); const intakeDocuments = state.intakeDocuments.map((doc) => doc.projectId === id ? { ...doc, projectId: targetProject.id, project: targetProject.name } : doc); return { projects: projects.sort((a, b) => a.name.localeCompare(b.name)), items, tasks, intakeDocuments }; }); queuePersist(); },
    addIntakeDocument: (input) => { const id = createId('DOC'); set((state: AppStore) => { const project = input.projectId ? state.projects.find((entry) => entry.id === input.projectId) : state.projects.find((entry) => entry.name.toLowerCase() === (input.project ?? '').toLowerCase()); const record: IntakeDocumentRecord = { id, name: input.name, kind: input.kind, disposition: 'Unprocessed', projectId: project?.id ?? input.projectId, project: project?.name ?? input.project ?? 'General', owner: input.owner ?? project?.owner ?? 'Unassigned', sourceRef: input.sourceRef ?? 'Uploaded to intake', uploadedAt: todayIso(), notes: input.notes ?? '', tags: input.tags ?? [] }; return { intakeDocuments: [record, ...state.intakeDocuments] }; }); queuePersist(); return id; },
    updateIntakeDocument: (id, patch) => { set((state: AppStore) => ({ intakeDocuments: state.intakeDocuments.map((doc) => doc.id !== id ? doc : { ...doc, ...patch, project: resolveProjectName(patch.projectId, patch.project, state.projects) }) })); queuePersist(); },
    setIntakeDocumentDisposition: (id, disposition, linkedFollowUpId) => { set((state: AppStore) => ({ intakeDocuments: state.intakeDocuments.map((doc) => doc.id === id ? { ...doc, disposition, linkedFollowUpId: linkedFollowUpId ?? doc.linkedFollowUpId } : doc) })); queuePersist(); },
    deleteIntakeDocument: (id) => { set((state: AppStore) => ({ intakeDocuments: state.intakeDocuments.filter((doc) => doc.id !== id) })); queuePersist(); },
  };
}
