import { defaultExecutionViews } from '../../lib/unifiedQueue';
import { getDefaultForwardedRules } from '../../lib/intakeRules';
import { defaultFollowUpFilters } from '../../lib/followUpSelectors';
import { getDefaultOutlookSettings } from '../../lib/outlookGraph';
import type { AppBusinessState, AppMetaState, AppUiState } from './types';

export const initialBusinessState: AppBusinessState = {
  items: [],
  contacts: [],
  companies: [],
  projects: [],
  tasks: [],
  intakeSignals: [],
  intakeDocuments: [],
  dismissedDuplicatePairs: [],
  duplicateReviews: [],
  outlookConnection: {
    settings: getDefaultOutlookSettings(),
    mailboxLinked: false,
    syncStatus: 'idle',
    syncCursorByFolder: { inbox: {}, sentitems: {} },
  },
  outlookMessages: [],
  droppedEmailImports: [],
  forwardedEmails: [],
  forwardedRules: getDefaultForwardedRules(),
  forwardedCandidates: [],
  forwardedLedger: [],
  forwardedRoutingAudit: [],
  intakeCandidates: [],
  intakeAssets: [],
  intakeBatches: [],
  intakeWorkCandidates: [],
  intakeReviewerFeedback: [],
};

export const initialUiState: AppUiState = {
  selectedId: null,
  search: '',
  projectFilter: 'All',
  statusFilter: 'All',
  activeView: 'All',
  followUpFilters: defaultFollowUpFilters,
  selectedFollowUpIds: [],
  followUpColumns: ['title', 'status', 'dueDate', 'nextTouchDate', 'priority', 'linkedTaskSummary'],
  savedFollowUpViews: [],
  followUpTableDensity: 'compact',
  followUpDuplicateModule: 'collapsed',
  itemModal: { open: false, mode: 'create', itemId: null },
  touchModalOpen: false,
  importModalOpen: false,
  mergeModal: { open: false, baseId: null, candidateId: null },
  draftModal: { open: false, itemId: null },
  taskModal: { open: false, mode: 'create', taskId: null },
  createWorkDraft: null,
  selectedTaskId: null,
  taskOwnerFilter: 'All',
  taskStatusFilter: 'All',
  queuePreset: 'Today',
  executionFilter: {},
  executionSort: 'queue_score',
  queueDensity: 'compact',
  savedExecutionViews: defaultExecutionViews,
  executionIntent: null,
  executionSelectedId: null,
  recordDrawerRef: null,
  activeRecordSurface: 'none',
  activeRecordRef: null,
  activeEditorMode: null,
  recordSurfaceSource: null,
  executionLaneSessions: {
    followups: {
      lane: 'followups',
      lastSelectedRecordId: null,
      lastProjectScope: null,
      lastSection: null,
      lastIntentLabel: null,
      lastSourceWorkspace: null,
      updatedAt: new Date(0).toISOString(),
    },
    tasks: {
      lane: 'tasks',
      lastSelectedRecordId: null,
      lastProjectScope: null,
      lastSection: null,
      lastIntentLabel: null,
      lastSourceWorkspace: null,
      updatedAt: new Date(0).toISOString(),
    },
  },
  lastExecutionRoute: null,
};

export const initialMetaState: AppMetaState = {
  hydrated: false,
  persistenceMode: 'loading',
  saveError: '',
  syncState: 'checking',
  cloudSyncStatus: 'unknown',
  loadedFromLocalRecoveryCache: false,
  unsavedChangeCount: 0,
  hasLocalUnsavedChanges: false,
  dirtyRecordRefs: [],
  lastCloudConfirmedAt: undefined,
  lastLocalWriteAt: undefined,
  lastFallbackRestoreAt: undefined,
  lastSyncedAt: undefined,
  lastFailedSyncAt: undefined,
  lastLoadFailureStage: undefined,
  lastLoadFailureMessage: undefined,
  lastLoadRecoveredWithLocalCache: undefined,
  sessionTrustState: 'healthy',
  sessionDegraded: false,
  sessionDegradedReason: 'none',
  sessionDegradedAt: undefined,
  sessionDegradedClearedByCloudSave: false,
  sessionTrustRecoveredAt: undefined,
  lastSuccessfulPersistAt: undefined,
  lastSuccessfulCloudPersistAt: undefined,
  persistenceActivity: [],
};
