import { defaultExecutionViews } from '../../lib/unifiedQueue';
import { getDefaultForwardedRules } from '../../lib/intakeRules';
import { defaultFollowUpFilters } from '../../lib/followUpSelectors';
import { getDefaultOutlookSettings } from '../../lib/outlookGraph';
import {
  DEFAULT_REMINDER_CENTER_SUMMARY,
  DEFAULT_REMINDER_PREFERENCES,
  DEFAULT_WORKSPACE_ATTENTION_COUNTS,
} from '../../lib/reminders';
import type { AppBusinessState, AppMetaState, AppUiState } from './types';

export const initialBusinessState: AppBusinessState = {
  items: [],
  contacts: [],
  companies: [],
  projects: [],
  tasks: [],
  intakeSignals: [],
  intakeDocuments: [],
  dismissedDuplicatePairs: [],
  duplicateReviews: [],
  outlookConnection: {
    settings: getDefaultOutlookSettings(),
    mailboxLinked: false,
    syncStatus: 'idle',
    syncCursorByFolder: { inbox: {}, sentitems: {} },
  },
  outlookMessages: [],
  droppedEmailImports: [],
  forwardedEmails: [],
  forwardedRules: getDefaultForwardedRules(),
  forwardedCandidates: [],
  forwardedLedger: [],
  forwardedRoutingAudit: [],
  intakeCandidates: [],
  intakeAssets: [],
  intakeBatches: [],
  intakeWorkCandidates: [],
  intakeReviewerFeedback: [],
};

export const initialUiState: AppUiState = {
  selectedId: null,
  search: '',
  projectFilter: 'All',
  statusFilter: 'All',
  activeView: 'All',
  followUpFilters: defaultFollowUpFilters,
  selectedFollowUpIds: [],
  followUpColumns: ['title', 'status', 'dueDate', 'nextTouchDate', 'priority', 'linkedTaskSummary'],
  savedFollowUpViews: [],
  followUpTableDensity: 'compact',
  followUpDuplicateModule: 'collapsed',
  itemModal: { open: false, mode: 'create', itemId: null },
  touchModalOpen: false,
  importModalOpen: false,
  mergeModal: { open: false, baseId: null, candidateId: null },
  draftModal: { open: false, itemId: null },
  taskModal: { open: false, mode: 'create', taskId: null },
  followUpInspector: { open: false, itemId: null },
  createWorkDraft: null,
  selectedTaskId: null,
  taskOwnerFilter: 'All',
  taskStatusFilter: 'All',
  queuePreset: 'Today',
  executionFilter: {},
  executionSort: 'queue_score',
  queueDensity: 'compact',
  savedExecutionViews: defaultExecutionViews,
  executionIntent: null,
  executionSelectedId: null,
  recordDrawerRef: null,
  activeRecordSurface: 'none',
  activeRecordRef: null,
  activeEditorMode: null,
  recordSurfaceSource: null,
  executionLaneSessions: {
    followups: {
      lane: 'followups',
      lastSelectedRecordId: null,
      lastProjectScope: null,
      lastSection: null,
      lastIntentLabel: null,
      lastSourceWorkspace: null,
      updatedAt: new Date(0).toISOString(),
    },
    tasks: {
      lane: 'tasks',
      lastSelectedRecordId: null,
      lastProjectScope: null,
      lastSection: null,
      lastIntentLabel: null,
      lastSourceWorkspace: null,
      updatedAt: new Date(0).toISOString(),
    },
  },
  lastExecutionRoute: null,
  supportWorkspaceSession: {
    projects: {
      selectedRecordId: null,
      searchQuery: '',
      sortKey: 'health',
      lastRouteTarget: null,
      lastRouteReason: null,
      lastLinkedSubset: null,
    },
    relationships: {
      selectedRecordId: null,
      searchQuery: '',
      sortKey: 'pressure',
      lastRouteTarget: null,
      lastRouteReason: null,
      lastLinkedSubset: null,
    },
  },
  toasts: [],
  undoStack: [],
  lastUndoCleanupAt: undefined,
  toastConfig: {
    maxVisible: 5,
    pauseOnHover: true,
    defaultDurationMs: {
      success: 3800,
      info: 4200,
      warning: 4800,
      error: 5200,
    },
  },
};

export const initialMetaState: AppMetaState = {
  hydrated: false,
  persistenceMode: 'loading',
  saveError: '',
  syncState: 'checking',
  cloudSyncStatus: 'unknown',
  localRevision: 0,
  lastLocalSavedAt: undefined,
  lastCloudConfirmedRevision: 0,
  activeSyncBatchId: undefined,
  pendingBatchCount: 0,
  localSaveState: 'idle',
  cloudSyncState: 'idle',
  trustState: 'healthy',
  loadedFromLocalRecoveryCache: false,
  unsavedChangeCount: 0,
  hasLocalUnsavedChanges: false,
  dirtyRecordRefs: [],
  lastCloudConfirmedAt: undefined,
  lastLocalWriteAt: undefined,
  lastFallbackRestoreAt: undefined,
  lastSyncedAt: undefined,
  lastFailedSyncAt: undefined,
  lastLoadFailureStage: undefined,
  lastLoadFailureMessage: undefined,
  lastLoadRecoveredWithLocalCache: undefined,
  sessionTrustState: 'healthy',
  sessionDegraded: false,
  sessionDegradedReason: 'none',
  sessionDegradedAt: undefined,
  sessionDegradedClearedByCloudSave: false,
  sessionTrustRecoveredAt: undefined,
  lastSuccessfulPersistAt: undefined,
  lastSuccessfulCloudPersistAt: undefined,
  lastConfirmedBatchId: undefined,
  lastConfirmedBatchCommittedAt: undefined,
  lastReceiptStatus: undefined,
  lastReceiptHashMatch: undefined,
  lastReceiptSchemaVersion: undefined,
  lastReceiptTouchedTables: undefined,
  lastReceiptOperationCount: undefined,
  lastReceiptOperationCountsByEntity: undefined,
  lastFailedBatchId: undefined,
  lastReceiptCommittedAt: undefined,
  lastFailureMessage: undefined,
  lastFailureClass: undefined,
  lastFailureNonRetryable: undefined,
  lastSanitizedFieldCount: undefined,
  lastSanitizedEntityTypes: undefined,
  unresolvedConflictCount: 0,
  verificationState: 'idle',
  lastVerificationRunId: undefined,
  lastVerificationStartedAt: undefined,
  lastVerificationCompletedAt: undefined,
  lastVerificationMatched: undefined,
  lastVerificationMismatchCount: undefined,
  lastVerificationBasedOnBatchId: undefined,
  lastVerificationFailureMessage: undefined,
  recoveryReviewNeeded: false,
  reviewedMismatchIds: [],
  verificationSummary: undefined,
  latestVerificationResult: undefined,
  outboxState: 'idle',
  unresolvedOutboxCount: 0,
  lastOutboxFlushAt: undefined,
  lastOutboxFailureAt: undefined,
  conflictReviewNeeded: false,
  openConflictCount: 0,
  lastConflictDetectedAt: undefined,
  lastConflictBatchId: undefined,
  conflictQueueSummary: undefined,
  lastConflictFailureMessage: undefined,
  conflictQueue: [],
  persistenceActivity: [],
  reminderPreferences: DEFAULT_REMINDER_PREFERENCES,
  reminderLedger: [],
  reminderCenterSummary: DEFAULT_REMINDER_CENTER_SUMMARY,
  workspaceAttentionCounts: DEFAULT_WORKSPACE_ATTENTION_COUNTS,
  pendingReminders: [],
  reminderPermissionState: 'default',
  connectivityState: 'online',
  offlineLoadState: 'none',
  pendingOfflineChangeCount: 0,
  lastConnectivityChangeAt: undefined,
  lastReconnectAttemptAt: undefined,
};
